type Users
{
    id: Int,
    name: String,
    family: String,
    phone: String
}

type Bardiademon
{
    id: String,
    name: String,
    email: String,
}

type Query
{
    user (name: String , family: String , phone: String): Users
    bardiademon : Bardiademon
}

type Result
{
    result: Boolean
}